{% set name = "pytest" %}
{% set version = "3.6.1" %}
{% set sha256 = "32c49a69566aa7c333188149ad48b58ac11a426d5352ea3d8f6ce843f88199cb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  entry_points:
    - py.test = py.test:main
    - pytest = py.test:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
  run:
    - atomicwrites >=1.0
    - attrs >=17.4.0
    - colorama  # [win]
    - funcsigs  # [py27]
    - more-itertools >=4.0
    - pluggy >=0.5,<0.7
    - py >=1.5.0
    - python
    - setuptools
    - six >=1.10.0

test:
  commands:
    - pytest -h
  imports:
    - pytest

about:
  home: https://docs.pytest.org/en/latest/
  license: MIT
  license_file: LICENSE
  summary: 'Simple and powerful testing with Python.'
  description: |
    The pytest framework makes it easy to write small tests, yet scales to
    support complex functional testing for applications and libraries.
  doc_url: https://docs.pytest.org/en/latest/
  dev_url: https://github.com/pytest-dev/pytest/

extra:
  recipe-maintainers:
    - flub
    - goanpeca
    - nicoddemus
    - ocefpaf
    - mingwandroid
